Style/ClassVars:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Naming/FileName:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/LineLength:
  # disable for comment-only lines and lines with URLs
  IgnoredPatterns: [
    '^(\A|\s)*#',
    'https?://'
  ]

Metrics/ClassLength:
  Max: 200

Metrics/PerceivedComplexity:
  Max: 15

Metrics/CyclomaticComplexity:
  Max: 15
